@startuml

class PemeriksaanLaboratoriumTri1Controller extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class Controller {
}

class BayiController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class KriteriaAnamnesisController extends Controller {
  +index()
  +create()
  +store()
  +show()
  +edit()
  +update()
  +destroy()
}

class RingkasanMtbsController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

@enduml
