@startuml

class Ibu2Controller extends Controller {
  +index()
  +create()
  +store()
  +show()
  +edit()
  +update()
  +destroy()
}

class KesehatanNifasController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class RingkasanKesimpulanNifasController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class PreeklampsiaAnamnesisController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class GrafikTbUPrController extends Controller {
  +index()
  +dataGrafik()
  +grafik()
  +create()
  +store()
  +show()
  +edit()
  +update()
  +destroy()
}

@enduml
