@startuml

class GrafikLingkarLakiController extends Controller {
  +index()
  +dataGrafik()
  +grafik()
  +create()
  +store()
  +show()
  +edit()
  +update()
  +destroy()
}

class RegisterController extends Controller {
  +index()
  +create()
  +store()
  +show()
  +edit()
  +update()
  +destroy()
}

class AnakController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class PelayananSdidtkController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class IbuBersalinController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

@enduml
