@startuml

class KmsLakiController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class GrafikBbUPrController extends Controller {
  +index()
  +dataGrafik()
  +grafik()
  +create()
  +store()
  +show()
  +edit()
  +update()
  +destroy()
}

class KesehatanBersalinController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class WaliController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class ImunisasiController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

@enduml
