@startuml

class PemeriksaanLaboratoriumTri3Controller extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class RiwayatKelahiranController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class KondisiKesehatanBumilController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class UmurKapsulAnakController extends Controller {
  +index()
  +create()
  +store()
  +show()
  +edit()
  +update()
  +destroy()
}

class GrafikImtPrController extends Controller {
  +index()
  +dataGrafik()
  +grafik()
  +create()
  +store()
  +show()
  +edit()
  +update()
  +destroy()
}

@enduml
