@startuml

class BbTbPerempuanController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class AmanatKendaraanController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class KmsPerempuanController extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class UsgTri1Controller extends BaseCrudController {
  +index()
  +create()
  +store()
  +update()
  +edit()
  +destroy()
  +ajax()
}

class RegisteredUserController extends Controller {
  +create()
  +store()
}

@enduml
